### ISSUE TITLE
Provide optional -config-dir flag that can be passed in

### ISSUE THREAD

**Issue by calvn** [cleung2010/chocolatey-packages#7]
Currently the `config-dir` directory is hardcoded to be set to `%PROGRAMDATA%\consul\config`, but it would be better if this can be changed if it's set during the install.

**Comment by 123BLiN** [comment]
Hello @cleung2010 ,

I'm very sorry but I was not able to test pull request - for some reason it is failed on:

```
choco install -fdv .\consul.0.6.4.nupkg -s $pwd
```

but I am not able to find the root cause.
Anyway it seams that this pull request should not affect anything, I hope you have a good env to test changes, sorry again :)
additional info was found here - https://github.com/chocolatey/choco/wiki/How-To-Parse-PackageParameters-Argument
pull request  - https://github.com/cleung2010/chocolatey-packages/pull/8

**Comment by calvn** [comment]
I think you have to do `-fdyv` to avoid chocolatey prompt. Anyhow this passed the CI, so should be good to merge.

**Comment by 123BLiN** [comment]
Hi @cleung2010 !

I was able to test it locally with some help from choco chat)
All works as expected except escaping " in params:

```
--packageParameters '-config-file=""%PROGRAMDATA%\consul\dsc-config\default.json"" -config-dir=%PROGRAMDATA%\consul\config1 -config-dir=""%PROGRAMDATA%\consul\extra-config""'
```

gives:

```
PS C:\GitHub\chocolatey-packages\consul> nssm get consul AppParameters 
agent -config-dir=%PROGRAMDATA%\consul\config -data-dir=%PROGRAMDATA%\consul\data -config-file=%PROGRAMDATA%\consul\dsc-config\default.json -config-dir=%PROGRAMDATA%\consul\config1 -config-dir=%PROGRAMDATA%\consul\extra-config
```

not """ not \" works, do you think you could approve to merge it without possibility to use spaces in config values?

Update:
This works:

```
choco install consul --packageParameters '-config-file=""\"%PROGRAMDATA%\consul\dsc-config\default.json\""" -config-dir=%PROGRAMDATA%\consul\config1 -config-dir=""\"%PROGRAMDATA%\consul\extra-config\"""'
```

**Comment by calvn** [comment]
This has been merged in and available in https://github.com/calvn/chocolatey-consul.
